version: '3'
services:
  api_service:
    container_name: ldds_api
    build: ./d2d-backend
    networks:
     - ldds-network
    ports:
     - "8080:8080"
  push_notif_service:
    container_name: push_notif_service
    image: appleboy/gorush
    volumes:
      - ../d2d-backend/notificationService/config.yml:/config.yml
    networks:
      - ldds-network
    ports:
      - "9000:9000"
  consumer_service:
      container_name: ldds_api
      build: ./ldds-message-queue
      networks:
       - ldds-network
      ports:
       - "8082:8082"
  redis:
    image: redis
    command: ["redis-server","--appendonly","yes"]
    hostname: redis
    ports:
         - "6379:6379"
    networks:
         - ldds-network
networks:
     ldds-network:
       driver: "bridge"